### ISSUE TITLE
dys n fet file has wrong md5sum

### ISSUE THREAD

**Issue by 0xygen8** [lazyzero/kkMulticopterFlashTool#10]
last 2 versions of the software (stable and beta) have the wrong md5sum for the dys n-fet file when using the 2015-04-19 release the 2014-09-30 md5sums are OK

exact error:

Flash the firmware from repository.
Flashing of firmware aborted. File is corrupted, MD5 does not match to the MD5 in the repository.

**Comment by lazyzero** [comment]
Thanks for pointing me to this.
The hashes are updated and should work now.
