### ISSUE TITLE
Flashtool Gui not showing up in window-11 x64. 

### ISSUE THREAD

**Issue by akshaymishra14** [lazyzero/kkMulticopterFlashTool#15]
I use x64 Windows-11 professional.  I have installed usbasp driver mentioned on site and the "testlibusb-win.exe" tool shows the details as: 
DLL version:	0.1.12.1
Driver version:	-1.-1.-1.-1

When I run Flash-tool (either stable version 0.77 or latest version 0.99) - the UI does not come up. I can see the process running in task-manager but I do not see the UI (it doesn't load in even 01 hour).  
The logging.txt file contains the message "INFO: Splash not loaded." - but no more details are available.

**Comment by Svein-Tore** [comment]
Welcome to the club.  I have the same problem. And I'm also running win 11.  Maybe a win 11 problem?

**Comment by lazyzero** [comment]
I am sorry but I can not add support for Win11 as I have non. Also the software is not maintained for years. 
Try it with a copy of Win10.

**Comment by Svein-Tore** [comment]
OK thanks Christian!

fre. 30. jun. 2023, 12:10 skrev Christian Moll ***@***.***>:
